#!/bin/bash
#
# yagni-edge     This shell script takes care of starting and stopping Tomcat
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: yagni-edge
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: yagni-edge
# Short-Description: start and stop yagni-edge
### END INIT INFO
 
tomcat_pid() {
  echo `ps aux | grep io.yagni.edge.vertx.YagniEdgeServer | grep -v grep | awk '{ print $2 }'`
}
 
start() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ] 
  then
    echo "yagni-edge is already running (pid: $pid)"
  else
    # Start yagni-edge
    echo "Starting yagni-edge"
    ulimit -n 100000
    umask 007
    /bin/su -p -s /bin/bash yagni-edge /usr/yagni-edge/bin/yagni-edge &
  fi
 
  return 0
}
 
stop() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "Stoping yagni-edge"
    kill -9 $pid
  else
    echo "yagni-edge is not running"
  fi
 
  return 0
}
 
case $1 in
start)
  start
;; 
stop)   
  stop
;; 
restart)
  stop
  start
;;
status)
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "yagni-edge is running with pid: $pid"
  else
    echo "yagni-edge is not running"
  fi
;; 
esac    
exit 0