#!/bin/bash
#
# ubiqesh-uplink     This shell script takes care of starting and stopping Tomcat
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: ubiqesh-uplink
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: ubiqesh-uplink
# Short-Description: start and stop ubiqesh-uplink
### END INIT INFO
 
tomcat_pid() {
  echo `ps aux | grep io.ubiqesh.uplink.vertx.UbiqeshUplinkServer | grep -v grep | awk '{ print $2 }'`
}
 
start() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ] 
  then
    echo "ubiqesh-uplink is already running (pid: $pid)"
  else
    # Start ubiqesh-uplink
    echo "Starting ubiqesh-uplink"
    ulimit -n 100000
    umask 007
    /bin/su -p -s /bin/bash ubiqesh-uplink /usr/ubiqesh-uplink/bin/ubiqesh-uplink &
  fi
 
  return 0
}
 
stop() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "Stoping ubiqesh-uplink"
    kill -9 $pid
  else
    echo "ubiqesh-uplink is not running"
  fi
 
  return 0
}
 
case $1 in
start)
  start
;; 
stop)   
  stop
;; 
restart)
  stop
  start
;;
status)
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "ubiqesh-uplink is running with pid: $pid"
  else
    echo "ubiqesh-uplink is not running"
  fi
;; 
esac    
exit 0