#!/bin/bash
#
# ubiqesh-edge     This shell script takes care of starting and stopping Tomcat
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: ubiqesh-edge
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: ubiqesh-edge
# Short-Description: start and stop ubiqesh-edge
### END INIT INFO
 
tomcat_pid() {
  echo `ps aux | grep io.ubiqesh.edge.vertx.UbiqeshEdgeServer | grep -v grep | awk '{ print $2 }'`
}
 
start() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ] 
  then
    echo "ubiqesh-edge is already running (pid: $pid)"
  else
    # Start ubiqesh-edge
    echo "Starting ubiqesh-edge"
    ulimit -n 100000
    umask 007
    /bin/su -p -s /bin/bash ubiqesh-edge /usr/ubiqesh-edge/bin/ubiqesh-edge &
  fi
 
  return 0
}
 
stop() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "Stoping ubiqesh-edge"
    kill -9 $pid
  else
    echo "ubiqesh-edge is not running"
  fi
 
  return 0
}
 
case $1 in
start)
  start
;; 
stop)   
  stop
;; 
restart)
  stop
  start
;;
status)
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo "ubiqesh-edge is running with pid: $pid"
  else
    echo "ubiqesh-edge is not running"
  fi
;; 
esac    
exit 0